### PR TITLE
Relax bounds for GHC 8.2

### PR DESCRIPTION
**Pull request by niteria**
GHC 8.2 ships with time-1.8.0.1

### CODE REVIEW

**Comment by ygale** [comment]
Thanks!

**Comment by niteria** [comment]
Thanks! Can I also ask you to update it on hackage?

**Comment by ygale** [comment]
It's [version 0.1.8](http://hackage.haskell.org/package/timezone-olson-0.1.8) on hackage.

**Comment by niteria** [comment]
Thanks again!

**Pull request merged**
